import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = fileURLToPath(new URL("../", import.meta.url));
const icons = {
  menu: "menu", search: "search", tune: "sliders-horizontal", help: "circle-help",
  settings: "settings", apps: "grid-3x3", plus: "plus", compose: "square-pen",
  inbox: "inbox", star: "star", clock: "clock", send: "send", draft: "file-pen-line",
  label: "tag", chevron: "chevron-down", more: "ellipsis-vertical", refresh: "rotate-cw",
  "arrow-left": "arrow-left", "arrow-right": "arrow-right", archive: "archive",
  trash: "trash-2", mail: "mail", snooze: "alarm-clock", report: "octagon-alert",
  primary: "mail", tag: "tag", people: "users", info: "info", close: "x",
  popout: "maximize-2", attach: "paperclip", calendar: "calendar-days", keep: "sticky-note",
  task: "list-checks", contact: "contact-round", gemini: "sparkles", minimize: "minus",
  logout: "log-out", "user-plus": "user-plus", reply: "reply", forward: "forward",
  external: "external-link", copy: "copy", check: "check", "mail-open": "mail-open",
  "square-check": "square-check", square: "square", filter: "list-filter"
};
const symbols = Object.entries(icons).map(([id, name]) => {
  const source = fs.readFileSync(path.join(root, "node_modules/lucide-static/icons", `${name}.svg`), "utf8");
  const content = source.match(/<svg\b[^>]*>([\s\S]*?)<\/svg>/)[1].trim();
  return `    <symbol id="i-${id}" viewBox="0 0 24 24">${content}</symbol>`;
});
const file = path.join(root, "index.html");
const html = fs.readFileSync(file, "utf8");
fs.writeFileSync(file, html.replace(/  <svg class="svg-defs"[\s\S]*?<\/svg>/, `  <svg class="svg-defs" aria-hidden="true" xmlns="http://www.w3.org/2000/svg">\n    <!-- Lucide icons, ISC license; see LICENSE-LUCIDE.txt. Generated by scripts/generate-icons.mjs. -->\n${symbols.join("\n")}\n  </svg>`));
fs.copyFileSync(path.join(root, "node_modules/lucide-static/LICENSE"), path.join(root, "LICENSE-LUCIDE.txt"));
